export const POSTS = [
  {
    title: "Ergonomic Steel Pants",
    image: "https://loremflickr.com/640/480/nature",
    comments: 15,
    likes: 84,
    country: "Huntington",
    id: "1",
  },
  {
    title: "Sleek Bronze Mouse",
    image: "https://loremflickr.com/640/480/nature",
    comments: 73,
    likes: 36,
    country: "Longmont",
    id: "2",
  },
  {
    title: "Gorgeous Rubber Bacon",
    image: "https://loremflickr.com/640/480/nature",
    comments: 40,
    likes: 9,
    country: "Independence",
    id: "3",
  },
  {
    title: "Ergonomic Steel Pants",
    image: "https://loremflickr.com/640/480/nature",
    comments: 15,
    likes: 84,
    country: "Huntington",
    id: "4",
  },
  {
    title: "Sleek Bronze Mouse",
    image: "https://loremflickr.com/640/480/nature",
    comments: 73,
    likes: 36,
    country: "Longmont",
    id: "5",
  },
  {
    title: "Gorgeous Rubber Bacon",
    image: "https://loremflickr.com/640/480/nature",
    comments: 40,
    likes: 9,
    country: "Independence",
    id: "6",
  },
];
